name: Build static library dependencies
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - master
    paths:
      - "duckdb.cpp"
      - "duckdb.h"
      - "duckdb.hpp"
jobs:
  darwin_amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: make deps.darwin.amd64
      - uses: actions/upload-artifact@v3
        with:
          name: darwin_amd64
          path: deps/darwin_amd64/libduckdb.a
          retention-days: 1
  darwin_arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: make deps.darwin.arm64
      - uses: actions/upload-artifact@v3
        with:
          name: darwin_arm64
          path: deps/darwin_arm64/libduckdb.a
          retention-days: 1
  linux_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: make deps.linux.amd64
      - uses: actions/upload-artifact@v3
        with:
          name: linux_amd64
          path: deps/linux_amd64/libduckdb.a
          retention-days: 1
  commit:
    runs-on: ubuntu-latest
    needs: [darwin_amd64, darwin_arm64, linux_amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: |
          rm -f deps/darwin_amd64/libduckdb.a
          rm -f deps/darwin_arm64/libduckdb.a
          rm -f deps/linux_arm64/libduckdb.a
      - uses: actions/download-artifact@v3
        with:
          name: darwin_amd64
          path: deps/darwin_amd64
      - uses: actions/download-artifact@v3
        with:
          name: darwin_arm64
          path: deps/darwin_arm64
      - uses: actions/download-artifact@v3
        with:
          name: linux_amd64
          path: deps/linux_amd64
      - name: Push static libraries
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-build static libraries
