name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  go_test:
    name: Main Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        go: [1.23, 1.24]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Main Tests
        run: |
          go test -v

  test_examples:
    name: Test Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.23, 1.24]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test Examples
        run: make test.examples
  test-arrow:
    name: Test Arrow
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.23, 1.24]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Arrow Tests
        run: go test -v -tags=duckdb_arrow
  test-dynamic-lib:
    name: Dynamic Lib Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go: [1.23, 1.24]
        os: [macos-13, macos-14, ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: "macos-13"
            filename: "libduckdb-osx-universal"
            ld_path_env_name: "DYLD_LIBRARY_PATH"
          - os: "macos-14"
            filename: "libduckdb-osx-universal"
            ld_path_env_name: "DYLD_LIBRARY_PATH"
          - os: "ubuntu-latest"
            filename: "libduckdb-linux-amd64"
            ld_path_env_name: "LD_LIBRARY_PATH"
          - os: "ubuntu-24.04-arm"
            filename: "libduckdb-linux-arm64"
            ld_path_env_name: "LD_LIBRARY_PATH"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Dynamic Lib Tests
        run: |
          make test.dynamic.lib FILENAME=${{ matrix.filename }} VERSION=v1.4.0
          CGO_ENABLED=1 CGO_LDFLAGS="-lduckdb -L${SRCDIR}dynamic-dir" ${{ matrix.ld_path_env_name }}=${SRCDIR}dynamic-dir go test -tags=duckdb_use_lib
  test-static-lib-darwin-arm64:
    name: Static Lib Tests Darwin ARM64
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go: [1.23, 1.24]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Static Lib Tests Darwin ARM64
        run: |
          make test.static.lib.darwin.arm64 VERSION=v1.4.0
          CGO_ENABLED=1 CPPFLAGS="-DDUCKDB_STATIC_BUILD" CGO_LDFLAGS="-lduckdb_static -lautocomplete_extension -lcore_functions_extension -licu_extension -ljson_extension -lparquet_extension -ltpcds_extension -ltpch_extension -lduckdb_fastpforlib -lduckdb_fmt -lduckdb_fsst -lduckdb_hyperloglog -lduckdb_mbedtls -lduckdb_miniz -lduckdb_pg_query -lduckdb_re2 -lduckdb_skiplistlib -lduckdb_utf8proc -lduckdb_yyjson -lduckdb_zstd -lc++ -L${SRCDIR}static-dir" go test -tags=duckdb_use_static_lib
